# Generated by Django 3.2 on 2024-10-25 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WarframeCampos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WarframeNombre', models.CharField(max_length=50)),
                ('CriticalUtility', models.FloatField()),
                ('CriticalDMG', models.FloatField()),
                ('StatusUtility', models.FloatField()),
            ],
        ),
    ]
